#!/usr/bin/env python3
"""Generate and verify the deterministic schema index used by language bindings."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
SCHEMA_DIR = ROOT / "schemas" / "v1"
OUTPUT = ROOT / "packages" / "contracts" / "generated" / "schema-index.json"
META_OUTPUTS = {
    ROOT / "packages/contracts/generated/typescript/schema-meta.ts": (
        '// @generated by scripts/generate.py; do not edit.\n'
        'export const SCHEMA_VERSION = "1.0.0" as const;\n'
        'export const SCHEMA_INDEX_SHA256 =\n'
        '  "{digest}" as const;\n'
    ),
    ROOT / "packages/contracts/generated/python/schema_meta.py": (
        '"""Generated schema identity. Do not edit."""\n\n'
        'SCHEMA_VERSION = "1.0.0"\n'
        'SCHEMA_INDEX_SHA256 = "{digest}"\n'
    ),
    ROOT / "packages/contracts/generated/rust/src/schema_meta.rs": (
        '//! Generated schema identity. Do not edit.\n\n'
        'pub const SCHEMA_VERSION: &str = "1.0.0";\n'
        'pub const SCHEMA_INDEX_SHA256: &str = "{digest}";\n'
    ),
}


def git_blob_sha1(data: bytes) -> str:
    header = f"blob {len(data)}\0".encode()
    return hashlib.sha1(header + data, usedforsecurity=False).hexdigest()


def build_index() -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    for path in sorted(SCHEMA_DIR.glob("*.schema.json")):
        raw = path.read_bytes()
        doc = json.loads(raw)
        rows.append(
            {
                "defs": sorted(doc.get("$defs", {}).keys()),
                "file": path.name,
                "git_blob_sha1": git_blob_sha1(raw),
                "id": doc.get("$id"),
                "title": doc.get("title"),
            }
        )
    return {"schema_version": "1.0.0", "schemas": rows}


def render_defs(values: list[str]) -> list[str]:
    compact = json.dumps(values)
    prefix = '      "defs": '
    if len(prefix) + len(compact) + 1 <= 100:
        return [f"{prefix}{compact},"]
    lines = ['      "defs": [']
    for index, value in enumerate(values):
        comma = "," if index + 1 < len(values) else ""
        lines.append(f"        {json.dumps(value)}{comma}")
    lines.append("      ],")
    return lines


def render_index(index: dict[str, Any]) -> str:
    lines = ["{", f'  "schema_version": {json.dumps(index["schema_version"])},', '  "schemas": [']
    schemas = index["schemas"]
    for position, row in enumerate(schemas):
        lines.append("    {")
        lines.extend(render_defs(row["defs"]))
        lines.extend(
            [
                f'      "file": {json.dumps(row["file"])},',
                f'      "git_blob_sha1": {json.dumps(row["git_blob_sha1"])},',
                f'      "id": {json.dumps(row["id"])},',
                f'      "title": {json.dumps(row["title"])}',
            ]
        )
        suffix = "," if position + 1 < len(schemas) else ""
        lines.append(f"    }}{suffix}")
    lines.extend(["  ]", "}"])
    return "\n".join(lines) + "\n"


def expected_outputs() -> dict[Path, str]:
    index_text = render_index(build_index())
    digest = hashlib.sha256(index_text.encode()).hexdigest()
    outputs = {OUTPUT: index_text}
    for path, template in META_OUTPUTS.items():
        outputs[path] = template.format(digest=digest)
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = expected_outputs()
    if args.check:
        drift = []
        for path, expected in outputs.items():
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual != expected:
                drift.append(path.relative_to(ROOT).as_posix())
        if drift:
            print("Generated contract drift:")
            for path in drift:
                print(f"- {path}")
            return 1
        print("Generated contracts: no drift")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print("Generated contract metadata updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
